## base image
FROM python:3.7.5-slim-buster AS compile-image

## install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc

## virtualenv
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

## add and install requirements
RUN pip install --upgrade pip && pip install pip-tools
COPY ./requirements.in .
RUN pip-compile requirements.in > requirements.txt && pip-sync
RUN pip install -r requirements.txt:

## build-image
FROM python:3.7.5-slim-buster AS runtime-image

## install nc
RUN apt-get update && \
    apt-get install -y --no-install-recommends netcat-openbsd

## copy Python dependencies from build image
COPY --from=compile-image /opt/venv /opt/venv


## set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PATH="/opt/venv/bin:$PATH"

## run server
CMD python /srv/app/web.py
